"""initial schema

Revision ID: 14a1a9249750
Revises: 
Create Date: 2026-06-30 01:39:26.182800

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '14a1a9249750'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='reward_status'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_category'), 'rewards', ['category'], unique=False)
    op.create_index(op.f('ix_rewards_status'), 'rewards', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('current_points', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('checkins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'analyzing', 'scored', 'rejected', name='checkin_status'), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('awarded_points', sa.Integer(), nullable=False),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('ai_advice', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkin_date', name='uq_checkins_user_date')
    )
    op.create_index(op.f('ix_checkins_checkin_date'), 'checkins', ['checkin_date'], unique=False)
    op.create_index(op.f('ix_checkins_status'), 'checkins', ['status'], unique=False)
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('point_transactions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('checkin_reward', 'redemption_cost', 'admin_adjustment', 'refund', name='point_transaction_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('related_type', sa.String(length=40), nullable=True),
    sa.Column('related_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_transactions_created_by'), 'point_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_point_transactions_related_id'), 'point_transactions', ['related_id'], unique=False)
    op.create_index(op.f('ix_point_transactions_related_type'), 'point_transactions', ['related_type'], unique=False)
    op.create_index(op.f('ix_point_transactions_type'), 'point_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_point_transactions_user_id'), 'point_transactions', ['user_id'], unique=False)
    op.create_table('redemptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'fulfilled', 'cancelled', 'refunded', name='redemption_status'), nullable=False),
    sa.Column('receiver_name', sa.String(length=80), nullable=True),
    sa.Column('receiver_phone', sa.String(length=32), nullable=True),
    sa.Column('receiver_address', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemptions_reward_id'), 'redemptions', ['reward_id'], unique=False)
    op.create_index(op.f('ix_redemptions_status'), 'redemptions', ['status'], unique=False)
    op.create_index(op.f('ix_redemptions_user_id'), 'redemptions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_table('checkin_score_dimensions',
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('dimension_code', sa.String(length=40), nullable=False),
    sa.Column('dimension_name', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkin_score_dimensions_checkin_id'), 'checkin_score_dimensions', ['checkin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkin_score_dimensions_checkin_id'), table_name='checkin_score_dimensions')
    op.drop_table('checkin_score_dimensions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_redemptions_user_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_status'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_reward_id'), table_name='redemptions')
    op.drop_table('redemptions')
    op.drop_index(op.f('ix_point_transactions_user_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_type'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_related_type'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_related_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_created_by'), table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_status'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_checkin_date'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_rewards_status'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_category'), table_name='rewards')
    op.drop_table('rewards')
    # ### end Alembic commands ###
